services:
  # app_proxy:
  #   expose:
  #     - "5172"
  #   ports:
  #     - "5172:5172"
  #   environment:
  #     # Frontend - serve the main UI
  #     APP_HOST: eltor-phoenix_web_1
  #     APP_PORT: 5172
  #     PROXY_AUTH_ADD: "false"
  #   networks:
  #     - default
  web:
    image: eltor/eltor:583cedfbf6203f65913645f4ab9a445f9c94d4a3-amd64
    init: true
    stop_grace_period: 1m
    ports:
      - "5172:5172"
      - "0.0.0.0:18058:18058" # Tor SOCKS proxy - explicitly bind to all interfaces
      - "0.0.0.0:9996:9996"   # Tor relay OR port - explicitly bind to all interfaces
    volumes:
      # TODO move to /home/user/.eltor
      - ${APP_DATA_DIR}/data/eltor:/home/user/code/eltor-app/backend/bin/data
      - ${APP_DATA_DIR}/data/phoenix:/home/user/.phoenix
    user: "1000:1000"
    environment:
      # Server binding configuration
      - BIND_ADDRESS=0.0.0.0
      - BACKEND_PORT=${BACKEND_PORT:-5172}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:5172}

      # App env vars
      - APP_ELTOR_USER_DIR=${APP_ELTOR_USER_DIR}
      - ACCEPT_INVALID_CERTS=true

      # LN env vars (from .env file)
      - APP_ELTOR_USE_PHOENIXD_EMBEDDED=${APP_ELTOR_USE_PHOENIXD_EMBEDDED}
      - APP_ELTOR_LN_IMPLEMENTATION=${APP_ELTOR_LN_IMPLEMENTATION}
      - APP_ELTOR_LN_BOLT12=${APP_ELTOR_LN_BOLT12}
      # APP_ELTOR_LN_CONFIG will be set by startup.sh because APP_ELTOR_USE_PHOENIXD_EMBEDDED=true
      # - APP_ELTOR_LN_CONFIG

      # Client Eltor Environment Variables
      - APP_ELTOR_TOR_ADDITIONAL_DIR_AUTHORITY=${APP_ELTOR_TOR_ADDITIONAL_DIR_AUTHORITY}
      - APP_ELTOR_TOR_NICKNAME=${APP_ELTOR_TOR_NICKNAME}
      - APP_ELTOR_TOR_DATA_DIRECTORY=${APP_ELTOR_TOR_DATA_DIRECTORY}
      - APP_ELTOR_TOR_SOCKS_PORT=${APP_ELTOR_TOR_SOCKS_PORT}
      - APP_ELTOR_TOR_CONTROL_PORT=${APP_ELTOR_TOR_CONTROL_PORT}
      - APP_ELTOR_TOR_HASHED_CONTROL_PASSWORD=${APP_ELTOR_TOR_HASHED_CONTROL_PASSWORD}
      - APP_ELTOR_TOR_CLIENT_ADDRESS=${APP_ELTOR_TOR_CLIENT_ADDRESS}
      - APP_ELTOR_TOR_PAYMENT_CIRCUIT_MAX_FEE=${APP_ELTOR_TOR_PAYMENT_CIRCUIT_MAX_FEE}

      # Relay Eltor Environment Variables
      - APP_ELTOR_TOR_RELAY_ADDITIONAL_DIR_AUTHORITY=${APP_ELTOR_TOR_RELAY_ADDITIONAL_DIR_AUTHORITY}
      - APP_ELTOR_TOR_RELAY_DATA_DIRECTORY=${APP_ELTOR_TOR_RELAY_DATA_DIRECTORY}
      - APP_ELTOR_TOR_RELAY_CONTACT=${APP_ELTOR_TOR_RELAY_CONTACT}
      - APP_ELTOR_TOR_RELAY_NICKNAME=${APP_ELTOR_TOR_RELAY_NICKNAME}
      - APP_ELTOR_TOR_RELAY_OR_PORT=${APP_ELTOR_TOR_RELAY_OR_PORT}
      - APP_ELTOR_TOR_RELAY_CONTROL_PORT=${APP_ELTOR_TOR_RELAY_CONTROL_PORT}
      - APP_ELTOR_TOR_RELAY_SOCKS_PORT=${APP_ELTOR_TOR_RELAY_SOCKS_PORT}
      - APP_ELTOR_TOR_RELAY_HASHED_CONTROL_PASSWORD=${APP_ELTOR_TOR_RELAY_HASHED_CONTROL_PASSWORD}
      - APP_ELTOR_TOR_RELAY_SANDBOX=${APP_ELTOR_TOR_RELAY_SANDBOX}
      - APP_ELTOR_TOR_EXIT_RELAY=${APP_ELTOR_TOR_EXIT_RELAY}
      - APP_ELTOR_TOR_RELAY_PAYMENT_RATE_MSATS=${APP_ELTOR_TOR_RELAY_PAYMENT_RATE_MSATS}
      - APP_ELTOR_TOR_RELAY_PAYMENT_INTERVAL=${APP_ELTOR_TOR_RELAY_PAYMENT_INTERVAL}
      - APP_ELTOR_TOR_RELAY_PAYMENT_INTERVAL_ROUNDS=${APP_ELTOR_TOR_RELAY_PAYMENT_INTERVAL_ROUNDS}
      - APP_ELTOR_TOR_RELAY_PAYMENT_CIRCUIT_MAX_FEE=${APP_ELTOR_TOR_RELAY_PAYMENT_CIRCUIT_MAX_FEE}

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eltor-phoenix_web_1:${BACKEND_PORT:-5172}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true
    