services:
  # app_proxy:
  #   environment:
  #     APP_HOST: $APP_HOST
  #     APP_PORT: 5175
  #     PROXY_AUTH_ADD: "false"
  #   networks:
  #     - default
  web:
    image: eltor/eltor-app@sha256:4d95f434cb942520edd57ab2e80b5043a71ec2a5fd507fd639449408c9fc9ca8
    init: true
    stop_grace_period: 1m
    ports:
      - "0.0.0.0:5174:5174"   # Backend API - explicitly bind to all interfaces
      - "0.0.0.0:5173:5173"   # Frontend web server - explicitly bind to all interfaces
      - "0.0.0.0:9740:9740"   # Lightning node - explicitly bind to all interfaces
      - "0.0.0.0:18058:18058" # Tor SOCKS proxy - explicitly bind to all interfaces
      - "0.0.0.0:9996:9996"   # Tor relay OR port
    volumes:
      - ${APP_DATA_DIR}/data/phoenix:/home/user/.phoenix
      - ${APP_DATA_DIR}/data/eltor/torrc:/home/user/code/eltor-app/backend/bin/torrc
      - ${APP_DATA_DIR}/data/eltor/torrc.relay:/home/user/code/eltor-app/backend/bin/torrc.relay
      - ${APP_DATA_DIR}/data/eltor/payments_sent.json:/home/user/code/eltor-app/backend/bin/payments_sent.json
      - ${APP_DATA_DIR}/data/eltor/payments_received.json:/home/user/code/eltor-app/backend/bin/payments_received.json
    user: "1000:1000"
    environment:
      - RUST_LOG=info
      - BACKEND_PORT=${BACKEND_PORT:-5174}
      - FRONTEND_PORT=${FRONTEND_PORT:-5173}
      - USE_PHOENIXD_EMBEDDED=${USE_PHOENIXD_EMBEDDED:-true}
      - PHOENIX_PORT=${PHOENIX_PORT:-9740}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT:-5174}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true
    