services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOST
      APP_PORT: 5173
      PROXY_AUTH_ADD: "false"
    networks:
      - default
  web:
    image: eltor/eltor-app:latest
    init: true
    stop_grace_period: 1m
    ports:
      - "0.0.0.0:8080:8080"   # Backend API - explicitly bind to all interfaces
      - "0.0.0.0:5173:5173"   # Frontend web server - explicitly bind to all interfaces
      - "0.0.0.0:9740:9740"   # Lightning node - explicitly bind to all interfaces
      - "0.0.0.0:18058:18058" # Tor SOCKS proxy - explicitly bind to all interfaces
      - "0.0.0.0:9996:9996"   # Tor relay OR port
    environment:
      - BACKEND_PORT=8080
      - FRONTEND_PORT=5173
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    name: umbrel_main_network
    external: true
    